# -*- coding: utf-8 -*-

## This file may be used under the terms of the GNU General Public
## License version 2.0 as published by the Free Software Foundation
## and appearing in the file LICENSE included in the packaging of
## this file. 
##
## This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
## WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
##
## See the NOTICE file distributed with this work for additional
## information regarding copyright ownership.

global languages_def
languages_def = {
    'aa':'Afar',
    'af':'Afrikaans',
    'af_ZA':'Afrikaans – Afrique du Sud',
    'am':'Amharique',
    'ar':'Arabe',
    'ar_OM':'Arabe – Oman',
    'ar_SA':'Arabe – Arabie saoudite',
    'ar_SY':'Arabe – Syrian Arab Republic',
    'ar_TN':'Arabe – Tunisie',
    'as':'Assamese',
    'ay':'Aymara',
    'az':'Azéri',
    'az_IR':'Azéri – Iran, Islamic Republic of',
    'be':'Biélorusse',
    'be@latin':'Biélorusse - Latin',
    'bg':'Bulgare',
    'bg_BG':'Bulgare – Bulgarie',
    'bn':'Bengali',
    'bn_IN':'Bengali – Inde',
    'bo':'Tibetan',
    'br':'Breton',
    'bs':'Bosniaque',
    'bs_BA':'Bosniaque – Bosnie-Herzégovine',
    'ca':'Catalan',
    'ca_ES':'Catalan – Espagne',
    'ca_ES@valencia':'Catalan - Espagne, Valence',
    'ca@valencia':'Catalan - Valence',
    'co':'Corsican',
    'cs':'Tchèque',
    'cs_CZ':'Tchèque – République tchèque',
    'cy':'Gallois',
    'cy_GB':'Gallois – Grande-Bretagne',
    'cz':'Langue inconnue',
    'da':'Danois',
    'da_DK':'Danois – Danemark',
    'de':'Allemand',
    'de_AT':'Allemand – Autriche',
    'de_CH':'Allemand – Suisse',
    'de_DE':'Allemand',
    'dk':'Langue inconnue',
    'dz':'Dzongkha',
    'el':'Grec',
    'el_GR':'Grec',
    'en':'Anglais',
    'en_AU':'Anglais – Australie',
    'en@boldquot':'Langue inconnue',
    'en_CA':'Anglais – Canada',
    'en_GB':'Anglais – Grande-Bretagne',
    'en@quot':'Langue inconnue',
    'en_SE':'Anglais – Suède',
    'en_US':'Anglais – États-Unis',
    'en_US@piglatin':'Langue inconnue',
    'en_ZA':'Anglais – Afrique du Sud',
    'eo':'Espéranto',
    'es':'Espagnol',
    'es_AR':'Espagnol – Argentine',
    'es_CL':'Espagnol – Chili',
    'es_CO':'Espagnol – Colombie',
    'es_CR':'Espagnol – Costa Rica',
    'es_DO':'Espagnol – République dominicaine',
    'es_EC':'Espagnol – Équateur',
    'es_ES':'Espagnol – Espagne',
    'es_GT':'Espagnol – Guatemala',
    'es_HN':'Espagnol – Honduras',
    'es_LA':'Espagnol – Lao People\'s Democratic Republic',
    'es_MX':'Espagnol – Mexique',
    'es_NI':'Espagnol – Nicaragua',
    'es_PA':'Espagnol – Panama',
    'es_PE':'Espagnol – Pérou',
    'es_PR':'Espagnol – Puerto Rico',
    'es_SV':'Espagnol – Salvador',
    'es_UY':'Espagnol – Uruguay',
    'es_VE':'Espagnol – Venezuela',
    'et':'Estonien',
    'et_EE':'Estonien – Estonie',
    'eu':'Basque',
    'eu_ES':'Basque – Espagne',
    'fa':'Persan',
    'fa_AF':'Persan – Afghanistan',
    'fa_IR':'Persan – Iran, Islamic Republic of',
    'fi':'Finnois',
    'fi_FI':'Finnois – Finlande',
    'fo':'Féroïen',
    'fo_FO':'Féroïen – Îles Féroé',
    'fr':'Français',
    'fr_CA':'Français – Canada',
    'fr_CH':'Français – Suisse',
    'fr_FR':'Français – France',
    'fr_LU':'Français – Luxembourg',
    'fy':'Frisian',
    'ga':'Irlandais',
    'gd':'Gaélique d\'Écosse',
    'gl':'Galicien',
    'gl_ES':'Galicien – Espagne',
    'gn':'Guarani',
    'gu':'Gujarati',
    'gv':'Manx',
    'ha':'Hausa',
    'he':'Hébreu',
    'he_IL':'Hébreu – Israël',
    'hi':'Hindi',
    'hr':'Croate',
    'hr_HR':'Croate – Croatie',
    'hu':'Hongrois',
    'hu_HU':'Hongrois – Hongrie',
    'hy':'Arménien',
    'ia':'Interlingua',
    'id':'Indonésien',
    'id_ID':'Indonésien – Indonésie',
    'is':'Islandais',
    'is_IS':'Islandais – Islande',
    'it':'Italien',
    'it_CH':'Italien – Suisse',
    'it_IT':'Italien – Italie',
    'iu':'Inuktitut',
    'ja':'Japonais',
    'ja_JP':'Japonais – Japon',
    'ka':'Géorgien',
    'kk':'Kazakh',
    'kl':'Groenlandais',
    'km':'Khmer',
    'km_KH':'Khmer – Cambodia',
    'kn':'Kannada',
    'ko':'Coréen',
    'ko_KR':'Coréen – Corée',
    'ku':'Kurde',
    'kw':'cornique',
    'ky':'Kirghiz',
    'la':'Latin',
    'lo':'Lao',
    'lt':'Lituanien',
    'lt_LT':'Lituanien – Lituanie',
    'lv':'Letton',
    'lv_LV':'Letton – Lettonie',
    'mg':'Malagasy',
    'mi':'Maori',
    'mk':'Macédonien',
    'mk_MK':'Macédonien – Macedonia, the Former Yugoslav Republic of',
    'ml':'Malayalam',
    'mn':'Mongol',
    'mr':'Marathi',
    'ms':'Malais',
    'ms_MY':'Malais – Malaisie',
    'mt':'Maltais',
    'my':'Burmese',
    'my_MM':'Burmese – Myanmar',
    'nb':'Norvégien bokmål',
    'nb_NO':'Norvégien bokmål – Norvège',
    'ne':'Nepali',
    'nl':'Néerlandais',
    'nl_BE':'Néerlandais – Belgique',
    'nl_NL':'Néerlandais – Pays-Bas',
    'nn':'Norvégien nynorsk',
    'nn_NO':'Norvégien nynorsk – Norvège',
    'no':'Norvégien',
    'no_NO':'Norvégien – Norvège',
    'no_NY':'Norvégien – NY',
    'nr':'Ndebele, South',
    'oc':'Provençal, occitan après 1500',
    'om':'Oromo',
    'or':'Oriya',
    'pa':'Panjabi',
    'pl':'Polonais',
    'pl_PL':'Polonais – Pologne',
    'ps':'Pushto',
    'pt':'Portugais',
    'pt_BR':'portugais – Brésil',
    'pt_PT':'portugais – Portugal',
    'qu':'Quechua',
    'rm':'Rhaeto-Romance',
    'ro':'roumain',
    'ro_RO':'roumain – Roumanie',
    'ru':'russe',
    'ru_RU':'russe – Russie',
    'rw':'Kinyarwanda',
    'sa':'Sanskrit',
    'sd':'Sindhi',
    'se':'Sami',
    'se_NO':'Sami – Norvège',
    'si':'Sinhalese',
    'sk':'slovaque',
    'sk_SK':'slovaque – Slovaquie',
    'sl':'slovène',
    'sl_SI':'slovène – Slovénie',
    'sm':'Samoan',
    'so':'Somali',
    'sp':'Langue inconnue',
    'sq':'albanais',
    'sq_AL':'albanais – Albanie',
    'sr':'serbe',
    'sr@ije':'Langue inconnue',
    'sr@latin':'Langue inconnue',
    'sr@Latn':'Langue inconnue',
    'sr_YU':'serbe – Yugoslavia',
    'ss':'Swati',
    'st':'Sotho',
    'sv':'suédois',
    'sv_SE':'suédois – Suède',
    'sw':'Swahili',
    'ta':'tamoul',
    'te':'Telugu',
    'tg':'tajik',
    'th':'thaï',
    'th_TH':'thaï – Thaïlande',
    'ti':'Tigrinya',
    'tk':'Turkmen',
    'tl':'Tagalog',
    'to':'tonga',
    'tr':'turc',
    'tr_TR':'turc – Turquie',
    'ts':'Tsonga',
    'tt':'Tatar',
    'ug':'Uighur',
    'uk':'ukrainien',
    'uk_UA':'ukrainien – Ukraine',
    'ur':'Urdu',
    'ur_PK':'Urdu – Pakistan',
    'uz':'Uzbek',
    'uz@cyrillic':'Langue inconnue',
    'vi':'vietnamien',
    'vi_VN':'vietnamien – Viêtnam',
    'wa':'Langue inconnue',
    'wo':'Wolof',
    'xh':'xhosa',
    'yi':'yiddish',
    'yo':'Yoruba',
    'zh':'chinois',
    'zh_CN':'chinois – Chine',
    'zh_HK':'chinois – Hong Kong',
    'zh_TW':'chinois – Taïwan',
    'zu':'zoulou'
}
